name: atlas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.0.0
  file_picker: ^11.0.0
  http_parser: ^4.0.0
  mime: ^2.0.0
  shared_preferences: ^2.2.0
  shared_preferences_web: ^2.2.0
  geolocator: ^14.0.2
  firebase_core: ^4.8.0
  cloud_firestore: ^6.4.0
  firebase_auth: ^6.5.0
  firebase_messaging: ^16.0.0
  agora_rtc_engine: ^6.5.0
  permission_handler: ^11.3.1
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

