// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1TZpB_JdVool83faV_P17A1_B_WPUjQ',
    appId: '1:565070198305:web:d7c89574e0810dd562d560',
    messagingSenderId: '565070198305',
    projectId: 'atlas007',
    authDomain: 'atlas007.firebaseapp.com',
    storageBucket: 'atlas007.firebasestorage.app',
    measurementId: 'G-N58TG47VKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmLFOEwa6OX8AhL0lKfbrDkMeQQ1QY0Ho',
    appId: '1:565070198305:android:7ad9e3553cee9ff562d560',
    messagingSenderId: '565070198305',
    projectId: 'atlas007',
    storageBucket: 'atlas007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_GDNI0Te56B9QXBAl03FY_OHGvooInZM',
    appId: '1:565070198305:ios:58fdcc461daa3f7762d560',
    messagingSenderId: '565070198305',
    projectId: 'atlas007',
    storageBucket: 'atlas007.firebasestorage.app',
    iosBundleId: 'com.orange.atlas.atlas',
  );
}
