// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4pzzUG7SJMH3QdTUeTkJpf632Qcfm75A',
    appId: '1:850337504996:web:3be722fb1e709107fad6f1',
    messagingSenderId: '850337504996',
    projectId: 'nexo-4c322',
    authDomain: 'nexo-4c322.firebaseapp.com',
    storageBucket: 'nexo-4c322.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2zcmqqYnmgZBZT44pOPboFEe1rdaNLU',
    appId: '1:850337504996:android:900f9b7b6509167ffad6f1',
    messagingSenderId: '850337504996',
    projectId: 'nexo-4c322',
    storageBucket: 'nexo-4c322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv7v2rAjKVoNO09uKDrU2qp6yFHLVJrfo',
    appId: '1:850337504996:ios:42cda114dc48bcc9fad6f1',
    messagingSenderId: '850337504996',
    projectId: 'nexo-4c322',
    storageBucket: 'nexo-4c322.firebasestorage.app',
    iosBundleId: 'com.orange.atlas.atlas',
  );
}
